import { NextResponse } from "next/server";

const products = [
  {
    id: "1",
    name: "آجیل شور",
    description: "ترکیبی از مغزها با طعم نمکی",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "2",
    name: "آجیل شیرین",
    description: "مغزهای شیرین و کاراملی",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "3",
    name: "آجیل مخلوط",
    description: "ترکیبی از انواع مغزها",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "4",
    name: "بادام هندی",
    description: "بادام هندی برشته شده",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "5",
    name: "پسته شور",
    description: "پسته نمکی و خوشمزه",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "6",
    name: "گردو",
    description: "گردوی تازه و مرغوب",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "7",
    name: "فندق",
    description: "فندق برشته شده",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "8",
    name: "تخمه آفتابگردان",
    description: "تخمه آفتابگردان نمکی",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "9",
    name: "بادام زمینی",
    description: "بادام زمینی بو داده",
    image: "/images/productLists.png",
    category: "خاندان لینا",
  },
  {
    id: "10",
    name: "آرد گندم",
    description: "آرد گندم تازه برای پخت نان",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "11",
    name: "آرد ذرت",
    description: "آرد ذرت ارگانیک",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "12",
    name: "آرد برنج",
    description: "آرد برنج سفید و باکیفیت",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "13",
    name: "نان تست",
    description: "نان تست گندمی",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "14",
    name: "نان سبوس دار",
    description: "نان سبوس‌دار سالم",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "15",
    name: "کیک شکلاتی",
    description: "کیک شکلاتی نرم و لذیذ",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "16",
    name: "بیسکویت کره‌ای",
    description: "بیسکویت با طعم کره",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "17",
    name: "مافین وانیلی",
    description: "مافین نرم و خوشمزه",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "18",
    name: "کلوچه سنتی",
    description: "کلوچه با طعم زعفران",
    image: "/images/productLists.png",
    category: "خانواده آردی",
  },
  {
    id: "19",
    name: "چیپس ساده",
    description: "چیپس نمکی ترد",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "20",
    name: "چیپس فلفلی",
    description: "چیپس با طعم فلفل قرمز",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "21",
    name: "چیپس پنیری",
    description: "چیپس با طعم پنیر",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "22",
    name: "چیپس سبزیجات",
    description: "ترکیبی از چیپس سبزیجات",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "23",
    name: "چیپس لیمویی",
    description: "چیپس با طعم لیمو ترش",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "24",
    name: "چیپس سرکه‌ای",
    description: "چیپس با طعم سرکه",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "25",
    name: "چیپس کچاپ",
    description: "چیپس با طعم کچاپ",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "26",
    name: "چیپس تند و آتشین",
    description: "چیپس با طعم تند و آتشین",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "27",
    name: "چیپس خامه‌ای",
    description: "چیپس با طعم خامه و پیاز",
    image: "/images/productLists.png",
    category: "خانواده چیپس",
  },
  {
    id: "28",
    name: "بیسکویت لینا",
    description: "بیسکویت خوشمزه لینا با طعم کره",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },
  {
    id: "29",
    name: "کیک لینا",
    description: "کیک نرم و شیرین لینا با طعم وانیل",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },
  {
    id: "30",
    name: "شکلات لینا",
    description: "شکلات تلخ با مغز فندق",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },
  {
    id: "31",
    name: "کراکر لینا",
    description: "کراکر ترد و خوشمزه",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },
  {
    id: "32",
    name: "نان لینا",
    description: "نان سبوس‌دار لینا برای صبحانه",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },
  {
    id: "33",
    name: "کلوچه لینا",
    description: "کلوچه نرم و مغزدار",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },
  {
    id: "34",
    name: "مینی دونات لینا",
    description: "دونات کوچک با روکش شکلات",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },
  {
    id: "35",
    name: "ویفر لینا",
    description: "ویفر کاکائویی لینا",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },
  {
    id: "36",
    name: "کرم کاکائو لینا",
    description: "کرم کاکائو فندقی",
    image: "/images/productLists.png",
    category: "خانواده آجیل",
  },

  {
    id: "37",
    name: "پاپ کورن کلاسیک",
    description: "پاپ کورن ساده و ترد",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },
  {
    id: "38",
    name: "پاپ کورن کاراملی",
    description: "پاپ کورن با روکش کارامل",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },
  {
    id: "39",
    name: "پاپ کورن پنیری",
    description: "پاپ کورن با طعم پنیر چدار",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },
  {
    id: "40",
    name: "پاپ کورن کره‌ای",
    description: "پاپ کورن با کره طبیعی",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },
  {
    id: "41",
    name: "پاپ کورن فلفلی",
    description: "پاپ کورن با چاشنی فلفل قرمز",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },
  {
    id: "42",
    name: "پاپ کورن عسلی",
    description: "پاپ کورن با روکش عسل",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },
  {
    id: "43",
    name: "پاپ کورن شکلاتی",
    description: "پاپ کورن با روکش شکلات تلخ",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },
  {
    id: "44",
    name: "پاپ کورن BBQ",
    description: "پاپ کورن با چاشنی باربیکیو",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },
  {
    id: "45",
    name: "پاپ کورن نمکی",
    description: "پاپ کورن با نمک دریا",
    image: "/images/productLists.png",
    category: "خانواده پاپ کورن",
  },

  {
    id: "46",
    name: "اسنک پنیری",
    description: "اسنک ترد با طعم پنیر",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
  {
    id: "47",
    name: "اسنک فلفلی",
    description: "اسنک با چاشنی فلفل قرمز",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
  {
    id: "48",
    name: "اسنک کره‌ای",
    description: "اسنک ترد با طعم کره",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
  {
    id: "49",
    name: "اسنک BBQ",
    description: "اسنک با چاشنی باربیکیو",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
  {
    id: "50",
    name: "اسنک سرکه‌ای",
    description: "اسنک با طعم سرکه",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
  {
    id: "51",
    name: "اسنک پیاز و جعفری",
    description: "اسنک خوشمزه با ترکیب پیاز و جعفری",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
  {
    id: "52",
    name: "اسنک کچاپ",
    description: "اسنک با طعم کچاپ گوجه",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
  {
    id: "53",
    name: "اسنک ذرت",
    description: "اسنک تهیه شده از آرد ذرت",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
  {
    id: "54",
    name: "اسنک پفکی",
    description: "اسنک پفکی ترد و خوشمزه",
    image: "/images/productLists.png",
    category: "خانواده اسنک",
  },
];

export async function GET() {
  return NextResponse.json(products);
}
