import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/styles/globals.scss";
import { Providers } from "@/app/providers";
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";

const IranSans = localFont({
  src: [
    {
      path: "../../../../app/fonts/DanaFaNum-UltraLight.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../../../app/fonts/DanaFaNum-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../../../app/fonts/DanaFaNum-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../../app/fonts/DanaFaNum-Medium.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../../../app/fonts/DanaFaNum-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../../../app/fonts/DanaFaNum-Black.woff2",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-dana",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({
  children,
  isMobile,
}: Readonly<{
  children: React.ReactNode;
  isMobile: boolean;
}>) {
  return (
    <html dir="rtl" className={`${IranSans.variable}`}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <link rel="apple-touch-icon" href="/icons/icon.jps" />
      </head>
      <body>
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
